version: "3.7"

services:
  api:
    container_name: busquedas-python
    image: python
    environment:
      - MONGO_URI=mongodb://mongo:27017/busquedas
      - APP_PORT=5001
    depends_on:
      - mongo
    volumes:
      - .:/api
    ports: ["5001:5001"]
    tty: true

  mongo:
    container_name: mongo-db-busquedas
    image: mongo
    volumes:
      - "./db:/data/db"
